apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
data:
  MYSQL_DATABASE: ZXhhbXBsZWRi # exampledb
  MYSQL_USER: ZXhhbXBsZXVzZXI= # exampleuser
  MYSQL_PASSWORD: ZXhhbXBsZXBhc3M= # examplepass

